#!/bin/bash

dates="$(date -u +"%d-%m-%Y" -d "-7 day")"

for i in $(seq -6 0); do
		dates="$dates\\n$(date -u +"%d-%m-%Y" -d "$i day")"
done

when=$(echo -e "$dates" | dmenu -p "When? ")

[[ "$when" == "" ]] && exit 1

amt=$(echo "" | dmenu -p "How much? ")

[[ "$amt" == "" ]] && exit 1

what=$(echo "" | dmenu -p "What? ")

[[ "$what" == "" ]] && exit 1

echo -e "$when\\n$amt\\n$what" | expenses
