#!/bin/bash

histfile="/tmp/search_hist"
hist=$(tac "$histfile" | uniq)

term=$(echo -n "$hist" | dmenu -l 10 -p "Enter search term: ")

[ "$term" == "" ] && exit 1

echo "$term" >> "$histfile"

x-www-browser "https://duckduckgo.com/?q=$term&t=h_&ia=web"
