#!/bin/bash
selected=$(echo -e "Lock\\nLogout\\nSuspend\\nHibernate\\nSuspend then hibernate\\nRestart\\nShutdown" | dmenu -i -l 7)

case $selected in
	"Lock") dmenu_select "$selected" "/home/atli/bin/lock" ;;
	"Logout") dmenu_select "$selected" "openbox --exit" ;;
	"Suspend") dmenu_select "$selected" "/usr/bin/systemctl suspend" ;;
	"Hibernate") dmenu_select "$selected" "/usr/bin/systemctl hibernate" ;;
	"Suspend then hibernate") dmenu_select "$selected" "/usr/bin/systemctl suspend-then-hibernate" ;;
	"Restart") dmenu_select "$selected" "/sbin/reboot" ;;
	"Shutdown") dmenu_select "$selected" "/sbin/shutdown -h now" ;;
esac	
